server:
  port: 8888
spring:
  application:
    name: config-service
# Config Git
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ailaries/ConfigReposity.git
          clone-on-start: true
          default-label: main
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh,busrefresh,health,info,env
# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka